export component Batt1Segment100 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  in property <bool> light_on;
  property <length> dimention;
  dimention: 70px;

  visible: !light_on;
  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT100.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment90 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT90.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment80 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT80.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment70 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT70.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment60 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT60.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment50 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT50.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment40 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT40.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment30 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 73px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT30.png");
    colorize: #121212;
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment20 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT20.png");
    colorize: #121212;
    width: 100%;
    height: 100%;
  }
}
export component Batt1Segment10 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT1_SEGMENT10.png");
    colorize: #131313;
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment100 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  in property <bool> light_on;
  property <length> dimention;
  dimention: 70px;

  visible: !light_on;
  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT100.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment90 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT90.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment80 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT80.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment70 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT70.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment60 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT60.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment50 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT50.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment40 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;

  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT40.png");
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment30 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 73px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT30.png");
    colorize: #121212;
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment20 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT20.png");
    colorize: #121212;
    width: 100%;
    height: 100%;
  }
}
export component Batt2Segment10 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;
  in property <bool> light_on;
  visible: !light_on;
  dimention: 70px;

  width: dimention;
  height: dimention;


  x: pos_x;
  y: pos_y;
  Image {
    source: @image-url("../images/BATT2_SEGMENT10.png");
    colorize: #131313;
    width: 100%;
    height: 100%;
  }
}

export component Batt1TitleCover inherits Rectangle {
  in property <bool> light_on;
  visible: !light_on;
  x: 179px;
  y: 50px;

    width: 100px;
    height: 20px;
    background: #101010;
}

export component Batt2TitleCover inherits Rectangle {
  in property <bool> light_on;
  visible: !light_on;
  x: 740px;
  y: 50px;

    width: 100px;
    height: 20px;
    background: #111111;
}