export component BotSegmentGreen1 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_GREEN_1_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentGreen2 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_GREEN_2_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentGreen3 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_GREEN_3_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue1 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_1_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue2 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_2_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue3 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_3_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue4 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_4_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue5 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_5_70X70.png");
    width: 100%;
    height: 100%;
  }
}
export component BotSegmentBlue6 inherits Rectangle {
  in property <length> pos_x;
  in property <length> pos_y;
  property <length> dimention;

  dimention: 70px;

  x: pos_x;
  y: pos_y;
  
  width: dimention;
  height: dimention;
  Image {
    source: @image-url("../images/REGEN_POWER_BLUE_6_70X70.png");
    width: 100%;
    height: 100%;
  }
}