export component SevenSegmentA inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_A_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentB inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_B_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentC inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_C_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentD inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_D_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentE inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_E_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentF inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_F_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}
export component SevenSegmentG inherits Rectangle {
  in property <length> pos_x;  
  in property <length> pos_y;
  in property <brush> custom_color;
  property <length> dimention;
  dimention: 120px;
  width: dimention;
  height: dimention;
  
  x: pos_x;
  y: pos_y;
  
  Image {
    source: @image-url("../images/SEVEN_SEGMENT_G_120x120.png");
    width: 100%; 
    height: 100%;
    colorize: custom_color;
    }
}

export component KmTitleCover inherits Rectangle {
  x: 680px;
  y: 364px;

    width: 89px;
    height: 32px;
    background: #171717;
}