import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { HundredsDisplay } from "hundreds.slint";
import { SmallSevenSegmentDisplay } from "smallsevensegment.slint";
import { SmallSevenSegmentMinusDisplay } from "smallsevensegmentminus.slint";

export component ClockDisplay inherits VerticalBox {
    in-out property <[bool]> minute_ones: [false,false,false,false,false,false];
    in-out property <[bool]> minute_tens: [false,false,false,false,false,false];
    in-out property <[bool]> hour_ones: [false,false,false,false,false,false];
    in-out property <[bool]> hour_tens: [false,false,false,false,false,false];
    in-out property <bool> minus: false;
    in-out property <bool> clock: false;
    in-out property <bool> date: false;
    in-out property <bool> temperature: false;
    in-out property <bool> colonColor: false;



    HorizontalBox {
        padding-left: 130px;
        Text {
        width: 50px;
        height: 35px;
        text: "Clock";
    color: clock  ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 35px;
        text: "Date";
    color: date  ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 35px;
        text: "Temperature";
    color: temperature  ? #1068f6 : #333;}}
    HorizontalBox {
        SmallSevenSegmentMinusDisplay { bits: hour_tens; minus: minus;}
        SmallSevenSegmentDisplay { bits: hour_ones; }
        VerticalBox {
            padding-top: 45px;
            Rectangle {
                width: 10px;
                height: 10px;
                background:  colonColor  ? #1068f6 : #333; // Red if colonColor is not 0, black otherwise
            }
            Rectangle {
                width: 10px;
                height: 10px;
                background: colonColor  ? #1068f6 : #333; // Red if colonColor is not 0, black otherwise
            }
        }
        
        SmallSevenSegmentDisplay { bits: minute_tens; }
        SmallSevenSegmentDisplay { bits: minute_ones; }
    }
}
    

