import { VerticalBox, HorizontalBox} from "std-widgets.slint";

export component DriveMode inherits HorizontalBox {
    in-out property <[bool]> bits: [true,false,false,false,false];

    Text {
        width: 50px;
        height: 15px;
        text: "D1";
    color: bits[4]   ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 15px;
        text: "D2";
    color: bits[3] ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 15px;
        text: "D3";
    color: bits[2] ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 15px;
        text: "P";
    color: bits[1]  ? #1068f6 : #333;}
    Text {
        width: 50px;
        height: 15px;
        text: "R";
    color: bits[0]  ? #1068f6 : #333;}
}