import { VerticalBox, HorizontalBox} from "std-widgets.slint";
import { SevenSegmentDisplay } from "sevensegment.slint";
import { HundredsDisplay } from "hundreds.slint";

export component IndicatorDisplay inherits VerticalBox {
    in-out property <bool> left_signal;
    in-out property <bool> mil_lamp;
    in-out property <bool> battery_alarm;
    in-out property <bool> AlarmRed;
    in-out property <bool> AlarmAmber;
    in-out property <bool> flasher;
    in-out property <bool> ABS;
    in-out property <bool> Derate;
    in-out property <bool> right_signal;
    in-out property <bool> headlights;
    in-out property <bool> farlights;
    in-out property <bool> taillights;
    in-out property <bool> READY;
    in-out property <bool> BLE;
    in-out property <bool> GPS;
    in-out property <bool> service_alarm;



    HorizontalBox {
        Text {
            width: 50px;
            height: 35px;
            text: "Left\nSignal";
        color: left_signal  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "Mil\nLamp";
        color: mil_lamp  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "Battery\nAlarm";
        color: battery_alarm  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "AlarmRed";
        color: AlarmRed  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "AlarmAmber";
        color: AlarmAmber  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "Flasher";
        color: flasher  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 15px;
            text: "ABS";
        color: ABS  ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 15px;
            text: "Derate";
        color: Derate ? #1068f6 : #333;}
        Text {
            width: 50px;
            height: 35px;
            text: "Right\nSignal";
        color: right_signal ? #1068f6 : #333;}
    }
    HorizontalBox {
        VerticalBox {
        width: 100px;
        Text {
            width: 70px;
            height: 35px;
            text: "Headlights";
        color: headlights  ? #1068f6 : #333;}
        Text {
            width: 70px;
            height: 35px;
            text: "Farlights";
        color: farlights ? #1068f6 : #333;}
        Text {
            width: 70px;
            height: 35px;
            text: "Taillights";
        color: taillights ? #1068f6 : #333;}
    }
    VerticalBox {
        padding-left: 80px;
        Text {
        width: 70px;
        height: 35px;
        text: "READY";
    color: READY ? #1068f6 : #333;}
    }
    
    VerticalBox {
        padding-left: 120px;
        width: 100px;
        Text {
            width: 70px;
            height: 35px;
            text: "BLE";
        color: BLE ? #1068f6 : #333;}
        Text {
            width: 70px;
            height: 35px;
            text: "GPS";
        color: GPS  ? #1068f6 : #333;}
        Text {
            width: 70px;
            height: 35px;
            text: "Service\nAlarm";
        color: service_alarm ? #1068f6 : #333;}
    }
    }
    
    
    
}