import { VerticalBox, HorizontalBox} from "std-widgets.slint";

export component PowerDisplay inherits HorizontalBox {
    in-out property <[bool]> powerbits: [false,false,false,false,false,false,false,false,false];

        HorizontalBox {
            Text {
                width: 100px/2;
                height: 80px/2;
                text: "power";
            color: #1068f6;}
                 
            Rectangle {
                height: 50px/2;
                width: 260px/2;
                background:  #000000;
                border-radius: 10px/2;
        
                Text {
                    x: 0px;
                    y: 30px;
                    width: 55px;
                    height: 20px;
                    text: "regen";
                color: #1068f6;}
                Text {
                    x: 220px/2;
                    y: 60px/2;
                    width: 55px;
                    height: 20px;
                    text: "max";
                color: #1068f6;}
                Rectangle { x: 10px/2; y: 5px/2;  width: 20px/2; height: 40px/2; background: powerbits[0]  ? #1068f6 : #333; }
                Rectangle { x: 35px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[1]  ? #1068f6 : #333; }
                Rectangle { x: 60px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[2]  ? #1068f6 : #333; }
                Rectangle { x: 80px/2; y: 5px/2; width: 5px/2; height: 40px/2; background: #000000; }
                Rectangle { x: 105px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[3]  ? #1068f6 : #333; }
                Rectangle { x: 130px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[4]  ? #1068f6 : #333; }
                Rectangle { x: 155px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[5]  ? #1068f6 : #333; }
                Rectangle { x: 180px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[6]  ? #1068f6 : #333; }
                Rectangle { x: 205px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[7]  ? #1068f6 : #333; }
                Rectangle { x: 230px/2; y: 5px/2; width: 20px/2; height: 40px/2; background: powerbits[8]  ? #1068f6 : #333; }

                
            }
        }
        
    

        
        
    
}